### ISSUE TITLE
Unrecognizable Death conflicts with other mods

### ISSUE THREAD

**Issue by PitchBright** [thetorine/thirstmod#12]
Some mods rely on being able to recognize how a player died. It appears as though ThirstMod manually deducts health in a way that causes the player to die, but other mods don't recognize the death type (since there was no "damage type" dealt to the player).

I believe that takes place in the "onTick" method here:
http://goo.gl/ahTwUq

```
                if ((player.getHealth() > 10) || (player.getHealth() > (ThirstMod.config.DEATH_FROM_THIRST ? 0 : (difSet == 3 ? 0 : 1)) && difSet >= 2)) {
                    //alternative to attackEntityFrom(DamageSource, Float) which was not working
                    player.setHealth(player.getHealth()-1f); 
                    player.addPotionEffect(new PotionEffect(Potion.confusion.id, 15 * 20, 1));
                    //disables regeneration to allow health loss.
                    //player.worldObj.getGameRules().setOrCreateGameRule("naturalRegeneration", "false");
                    timer = 0;
                }
```

Instead of using:
player.setHealth(player.getHealth()-1f); 

Can you use the following instead:
player.attackEntityFrom(DamageSource.generic, 1F);

**Comment by ghost** [comment]
Damage source "thirst" will be fine. Im using similar way to get player damage in my apocalypse mod.

**Comment by thetorine** [comment]
"attackEntityFrom(DamageSource, Integer)" wasn't working before but I'll look into it again.
