### ISSUE TITLE
The thirst bar prevents Smart Moving GUI from showing.

### ISSUE THREAD

**Issue by Leeo97one** [thetorine/thirstmod#15]
Install Smart Moving with Thirst Mod, start a new world, do a sprint with the Smart Moving key and you won't see the exhaustion bar by this way. And if you try to do a charged jump, you also won't see the jump bar.

Minecraft : 1.7.10
Thirst Mod : 1.8.14
Smart Moving : 15.5
Forge : 10.13.3.1401-1710ls

**Comment by PitchBright** [comment]
In the config file:

```
# Moves the ThirstBar to be above the health bar.
B:"Meter on leftside"=false
```

**Comment by PitchBright** [comment]
I use both ThirstMod and Smart Moving, and the Smart Moving Exhaustion icons show up over top of the thirst drops (right hand side)

**Comment by Leeo97one** [comment]
Ok thanks, I will try that ^^
And for the jump bar ?

**Comment by PitchBright** [comment]
No idea. I haven't tried the Thirst on the left. It'll probably be the same situation though, unfortunately.

Basically… there's only so many things you can put in one spot.

**Comment by Leeo97one** [comment]
Sorry, it is a mistake from me. The Smart Moving GUI isn't messed up.

**Comment by PitchBright** [comment]
What was the mistake? (I like it when people explain their problem and the solution because when other people google the same question… they'll be able get the answer.)

**Comment by Leeo97one** [comment]
In fact, I can see the Smart Moving GUI with the Thirst Mod. But I have some problems with Smart Moving and sometimes the GUI does not appear and I thought it was the fault of the Thirst Mod (whereas not).

**Comment by PitchBright** [comment]
Right… me too. Did you find the solution?

**Comment by Leeo97one** [comment]
No, it seems to be random :-/
Do you use Optifine too ?

**Comment by PitchBright** [comment]
Yes, I do use Optifine.

My theory was that it was something about switching to Creative mode, that was making the icons disappear. Have you been switching back and forth between Creative and Survival?

**Comment by Leeo97one** [comment]
Yes, it is possible.
For my part, it seems that occurs when I start a game (solo or multi). I suspect Optifine because it changes the rendering a lot.
