### ISSUE TITLE
life lost is not recovered

### ISSUE THREAD

**Issue by lightning02** [thetorine/thirstmod#17]
Version: thirstmod-1.8.9

I have a problem.. life lost is not recovered,nor when you have the full bar appetite, nor when you have the bar full of thirsty and nor when you have both full.
I have add also the drink pack #1 and #2. is maybe because I have to use only 1 of the 2 #drinkpacks?
This appens only after the effect of sickness disappears. 
Once you get half hearted because of thirst, not being able to die, the effect sickness stops and when it disappears, after you can't take life in any way.. neither eating nor drinking although the bar food and thirst are again full..

with version: 1.8.8 
In this version that error not appens, however many times when you reach 0 thristy you don't even lose hp.

Someone can help me?

**Comment by PitchBright** [comment]
Try the most recent version. Read the changelogs so see what all has changed since v1.8.8 & 9.

**Comment by lightning02** [comment]
The most recent version for 1.7.10 is 1.8.9, there is maybe a new one? 
With version 1.8.8 and 1.8.9 i have problems.. ( described before )

**Comment by thetorine** [comment]
I think I fixed this in an earlier version. The newest version is 1.8.14, so could you use that and report if there are any issues?

**Comment by lightning02** [comment]
Yeah, you fixed this, but only for minecraft 1.8..
Could you somehow make one for minecraft 1.7 10  too? Many people use mods for that version still..

**Comment by thetorine** [comment]
I haven't released an update for Minecraft 1.8. The latest version 1.8.14
is for Minecraft 1.7.10.

**Comment by lightning02** [comment]
ohw, sorry then, I maybe have been check bad in your dropbox download, i was sure the maximum version available was 1.8.9, my bad, thanks alot!
I'll try this version and tell u if i find issues!!
