### ISSUE TITLE
rain collector - it fills when placed in dry biome

### ISSUE THREAD

**Issue by ghost** [thetorine/thirstmod#5]
I have custom biomes where no rain, but rain collector filling with water if placed in these dry biomes.

**Comment by thetorine** [comment]
Will fix if I can tell if the biome has rain enabled in code.

**Comment by ghost** [comment]
Im using TerrainControll mod to generate custom biome. When Im in the biome where I see no rain particles, raincollector still working. Im expect not working in dry biomes.

**Comment by thetorine** [comment]
Hopefully fixed in the newest release. (1.8.13)
