### ISSUE TITLE
Drink Brewer GUI animation glitch

### ISSUE THREAD

**Issue by PitchBright** [thetorine/thirstmod#6]
http://i.imgur.com/XeyCyJC.png

**Comment by thetorine** [comment]
Can you tell me what mode the Minecraft game was in when this occurred. Fullscreen mode, small window or large window?

**Comment by thetorine** [comment]
Never mind. Reproduced the issue. Will fix.
Thanks.

**Comment by PitchBright** [comment]
The brewing progress arrow/bar also doesn't seem to work either.
